package com.simagis.pyramid.dicom;

import java.io.File;
import java.io.IOException;

// This class is created for debugging purposes only and can be rewritten
// according to changes in the IDEA modules configuration.
// The current classPath is not actual.
class SimagisCaller {
    private static boolean VSI = Boolean.getBoolean("com.simagis.pyramid.imageio.dicom.server.VSI");

    public static void main(String args[]) throws IOException, InterruptedException {
        if (args.length == 0) {
            System.out.println("Usage: " + SimagisCaller.class.getName() + " SIMAGIS_root_directory");
            return;
        }
        String root = args[0];
        // The list below is for editing and testing SIMAGIS behaviour with different classpath
        String classPath = root + "jre/lib/charsets.jar;"
            + root + "jre/lib/deploy.jar;"
            + root + "jre/lib/javaws.jar;"
            + root + "jre/lib/jce.jar;"
            + root + "jre/lib/jfr.jar;"
            + root + "jre/lib/jfxrt.jar;"
            + root + "jre/lib/jsse.jar;"
            + root + "jre/lib/management-agent.jar;"
            + root + "jre/lib/plugin.jar;"
            + root + "jre/lib/resources.jar;"
            + root + "jre/lib/rt.jar;"
            + root + "jre/lib/ext/access-bridge-32.jar;"
            + root + "jre/lib/ext/dnsns.jar;"
            + root + "jre/lib/ext/jaccess.jar;"
            + root + "jre/lib/ext/localedata.jar;"
            + root + "jre/lib/ext/sunec.jar;"
            + root + "jre/lib/ext/sunjce_provider.jar;"
            + root + "jre/lib/ext/sunmscapi.jar;"
            + root + "jre/lib/ext/sunpkcs11.jar;"
            + root + "jre/lib/ext/zipfs.jar;"
            + root + "trunk/bin/af/classes;"
            + root + "trunk/bin/ii/classes;"
            + root + "trunk/bin/lib/log4j.jar;"
            + root + "trunk/bin/metrology/classes;"
            + root + "trunk/bin/mms/classes;"
            + root + "trunk/bin/afGradient/classes;"
            + root + "trunk/bin/afWizard/classes;"
            + root + "trunk/bin/classes;"
            + root + "trunk/bin/src-image-classes;"
            + root + "trunk/bin/src-imagejava2-classes;"
            + root + "trunk/bin/algart/classes;"
            + root + "trunk/bin/algorithm-lib/classes;"
            + root + "trunk/bin/plugin3/classes;"
            + root + "trunk/bin/algart-extensions/classes;"
            + root + "trunk/bin/lib/json.jar;"
            + root + "trunk/SimagisLive/LiveUsersJson/classes;"
            + root + "trunk/bin/alloy/lib/alloy.jar;"
            + root + "trunk/bin/lib/batik.jar;"
            + root + "trunk/bin/lib/fop.jar;"
            + root + "trunk/bin/lib/jimi1_0.jar;"
            + root + "trunk/bin/lib/looks-1.3.1.jar;"
            + root + "trunk/bin/lib/Tidy.jar;"
            + root + "trunk/bin/lib/WMFWriter.jar;"
            + root + "trunk/bin/lib/swing-layout-1.0.jar;"
            + root + "trunk/bin/lib/substance.jar;"
            + root + "trunk/bin/lib/substance-watermark-pack.jar;"
            + root + "trunk/bin/lib/itext.jar;"
            + root + "trunk/bin/lib/smack.jar;"
            + root + "trunk/bin/lib/smackx.jar;"
            + (VSI ? "" :
            root + "trunk/bin/lib/jai_core.jar;"
                + root + "trunk/bin/lib/jai_codec.jar;"
                + root + "trunk/bin/lib/jai_imageio.jar;")
            + root + "trunk/bin/lib/clibwrapper_jiio.jar;"
            + root + "trunk/bin/lib/avalon-framework-cvs-20020315.jar;"
            + root + "trunk/bin/AlgartImagesP3/classes;"
            + root + "trunk/bin/algorithm-image-recognition/classes;"
            + root + "trunk/bin/alloy/classes;"
            + root + "trunk/bin/auto/classes;"
            + root + "trunk/bin/src-imagesurface-classes;"
            + root + "trunk/bin/src-afmimage-classes;"
            + root + "trunk/bin/fitting/classes;"
            + root + "trunk/bin/lib/Jama-1.0.2.jar;"
            + root + "trunk/bin/src-metrology-classes;"
            + root + "trunk/bin/autoscan/classes;"
            + root + "trunk/bin/autoscanSA/classes;"
            + root + "trunk/bin/image-stitching/classes;"
            + root + "trunk/bin/SimagisGraphicsCE/classes;"
            + root + "trunk/bin/SimagisGraphics/classes;"
            + root + "trunk/bin/classify/classes;"
            + root + "trunk/bin/nomenclature2simagis/classes;"
            + root + "trunk/bin/nomenclature/classes;"
            + root + "trunk/bin/Customer/kalina/classes;"
            + root + "trunk/bin/Customer/KUMZ/classes;"
            + root + "trunk/bin/distrBuilder/classes;"
            + root + "trunk/bin/etchedwafers/classes;"
            + root + "trunk/bin/statistics/classes;"
            + root + "trunk/bin/GDS/classes;"
            + root + "trunk/bin/HugeImageDrawing/classes;"
            + root + "trunk/bin/ExcelTransform/classes;"
            + root + "trunk/bin/ii-simagis/classes;"
            + root + "trunk/bin/mms/src-ProScanII-classes;"
            + root + "trunk/bin/mms/src-test-classes;"
            + root + "trunk/bin/mmsLeica/classes;"
            + root + "trunk/bin/mmsWizard/classes;"
            + root + "trunk/bin/plafSimagisWin/classes;"
            + root + "trunk/bin/plugin3-simagis/classes;"
            + root + "trunk/bin/simagis-image-recognition/classes;"
            + root + "trunk/bin/SimagisBigTIFF/classes;"
            + root + "trunk/bin/SimagisImageMagick/classes;"
            + root + "trunk/SimagisLive/SimagisLiveP3/classes;"
            + root + "trunk/SimagisLive/SimagisLiveLib/classes;"
            + root + "trunk/aws-java-sdk-1.0.11/lib/aws-java-sdk-1.0.11.jar;"
            + root + "trunk/apache-commons/lib/commons-logging-1.1.1.jar;"
            + root + "trunk/apache-commons/lib/commons-httpclient-3.1.jar;"
            + root + "trunk/apache-commons/lib/commons-codec-1.4.jar;"
            + root + "trunk/SimagisLive/RemotePlanePyramid/classes;"
            + root + "trunk/SimagisLive/RemotePlanePyramidServer/classes;"
            + (VSI ? "" :
            root + "trunk/SimagisLive/jai-imageio-1_2/lib/ext/jai_imageio.jar;")
            + root + "trunk/out-default/production/SimagisLiveAttr;"
//            + root + "trunk/bin/lib/imageio-ext-tiff-1.1.3.jar;"
//            + root + "trunk/bin/lib/imageio-ext-streams-1.1.3.jar;"
//            + root + "trunk/bin/lib/imageio-ext-utilities-1.1.3.jar;"
            + root + "trunk/SimagisLive/SimagisLivePB/classes;"
            + root + "trunk/bin/SimagisRegedit/classes;"
            + root + "trunk/bin/ipc/classes;"
            + root + "trunk/bin/SimagisSemi/classes;"
            + root + "trunk/bin/SimagisSemiDB/classes;"
            + root + "trunk/bin/src-imagestitching-classes;"
            + root + "trunk/bin/src-view3d-classes;"
            + root + "trunk/bin/lib/vecmath.jar;"
            + root + "trunk/bin/lib/j3dcore.jar;"
            + root + "trunk/bin/lib/j3dutils.jar;"
            + root + "trunk/bin/lib/jfreechart-1.0.13.jar;"
            + root + "trunk/bin/lib/jcommon-1.0.16.jar;"
            + root + "trunk/bin/classify2/classes;"
            + root + "trunk/bin/classify2-simagis/classes;"
            + root + "trunk/bin/SimagisParticlesMeas/classes;"
            + root + "trunk/bin/color/classes;"
            + root + "trunk/bin/color-simagis/classes;"
            + root + "trunk/bin/contours2d/classes;"
            + root + "trunk/bin/contours2d2simagis/classes;"
            + root + "trunk/bin/mesoplant/classes;"
            + root + "trunk/bin/microhardness/classes;"
            + root + "trunk/bin/mmsLeicaDM456K/classes;"
            + root + "trunk/bin/mmsMarzhauser/classes;"
            + root + "trunk/bin/mmsStub/classes;"
            + root + "trunk/bin/multiphase/classes;"
            + root + "trunk/bin/panorama/classes;"
            + root + "trunk/bin/src-petro-classes;"
            + root + "trunk/bin/TriangulationQuadEdge/classes;"
            + root + "trunk/bin/regiongrow/classes;"
            + root + "trunk/bin/petro-ext/classes;"
            + root + "trunk/bin/src-nanotube-geometry-classes;"
            + root + "trunk/bin/src-ore-classes;"
            + root + "trunk/bin/src-srid-classes;"
            + root + "trunk/bin/vectors2d/classes;"
            + root + "trunk/bin/vectors2d2simagis/classes;"
            + root + "trunk/bin/Customer/TI/classes;"
            + root + "trunk/bin/lib/JGDS.jar;"
            + root + "trunk/bin/lib/JBNT.jar;"
            + root + "trunk/bin/Customer/3DMicrochipAnalysis/classes;"
            + root + "trunk/bin/ipc-canvas/classes;"
            + root + "trunk/bin/lib/mail.jar;"
            + root + "trunk/bin/Customer/TSMC/classes;"
            + root + "trunk/bin/SimagisRecognitionOfParallels/classes;"
            + root + "trunk/bin/Semi/classes;"
            + root + "trunk/bin/src-MagicTech-classes;"
            + root + "trunk/bin/wgraph-processing/classes;"
            + root + "trunk/MineralS7/MineralsDB/classes;"
            + root + "trunk/MineralS7/MineralsDBJson/classes;"
            + root + "trunk/MineralS7/MineralsDBJson/lib/jackson-core-asl-1.7.2.jar;"
            + root + "trunk/MineralS7/MineralsDBJson/lib/jackson-mapper-asl-1.7.2.jar;"
            + root + "trunk/bin/ComGeom2d-lib/MathAlg/classes;"
            + root + "trunk/bin/ComGeom2d-lib/Planargraph/classes;"
            + root + "trunk/bin/ComGeom2d-lib/Planargraph-P3/classes;"
            + root + "trunk/bin/SimagisMatrixDemo/classes;"
            + root + "trunk/ImageJ/ImageJP3/classes;"
            + root + "trunk/ImageJ/ij144/ij.jar;"
            + root + "trunk/MineralS7/MineralS7/classes;"
            + root + "trunk/bin/Customer/Biomed/classes;"
            + root + "trunk/bin/ComGeom2d-lib/Triangle/classes;"
            + root + "trunk/bin/Customer/Skin-UZI/classes;"
            + root + "trunk/Jenoptik/iiJenoptikProgRes/classes;"
            + root + "trunk/OpenSlide/OpenSlideP3/classes;"
            + root + "trunk/OpenSlide/openslide-win32/openslidejava.jar;"
            + root + "trunk/bin/CompareWithStandards/classes;"
            + root + "trunk/Ilastik/IlastikP3/classes;"
            + root + "trunk/bin/lib/jhdfobj.jar;"
            + root + "trunk/bin/lib/jhdf5obj.jar;"
            + root + "trunk/bin/lib/jhdf5.jar;"
            + root + "trunk/bin/lib/jhdf4obj.jar;"
            + root + "trunk/bin/lib/jhdf.jar;"
            + root + "trunk/bin/SimagisBigTIFFp3/classes;"
            + root + "trunk/bin/iiLucam/classes;"
            + root + "trunk/SimagisLive/LiveUpload/classes;"
            + root + "trunk/SimagisLive/LiveUpload/lib/jgoodies-looks-2.5.1.jar;"
            + root + "trunk/SimagisLive/LiveUpload/lib/jgoodies-common-1.3.1.jar;"
            + root + "trunk/bin/Customer/bochvara/classes;"
            + root + "trunk/bin/iiStub/classes;"
            + root + "trunk/bin/Customer/kzts/classes;"
            + root + "trunk/SimagisLive/RemotePlanePyramidOpenSlide/classes;"
            + root + "trunk/out-default/production/PlanePyramidBioFormats;"
            + root + "trunk/out-default/production/OlympusVSI;"
            + root + "trunk/out-default/production/PlanePyramidSourceOlympus;"
            + root + "trunk/SLF4J/1.6.4/jcl-over-slf4j-1.6.4.jar;"
            + root + "trunk/SLF4J/1.6.4/log4j-over-slf4j-1.6.4.jar;"
            + root + "trunk/SLF4J/1.6.4/slf4j-api-1.6.4.jar;"
            + root + "trunk/SLF4J/1.6.4/slf4j-jdk14-1.6.4.jar;"
//            + root + "trunk/Loci/jar/bio-formats-for-developers-daily/bio-formats.jar;"
            + root + "trunk/Loci/jar/bio-formats-for-developers-daily/loci-common.jar;"
//            + root + "trunk/Loci/jar/bio-formats-for-developers-daily/mdbtools-java.jar;"
//            + root + "trunk/Loci/jar/bio-formats-for-developers-daily/ome-xml.jar;"
//            + root + "trunk/Loci/jar/bio-formats-for-developers-daily/poi-loci.jar;"
            + root + "trunk/Loci/jar/bio-formats-for-developers-daily/scifio.jar;"
            + root + "trunk/Loci/jar/kryo/kryo-2.21.jar;"
            + root + "trunk/out-default/production/PlanePyramidSourceNDPRead;"
            + root + "trunk/bin/lib/jna.jar;"
            + root + "trunk/bin/lib/platform.jar;"
            + root + "trunk/bin/iiAVTJni/classes;"
            + root + "trunk/out-default/production/SimagisLiveJsonToSolr;"
            + root + "trunk/apache-solr-solrj/4.0.0/apache-solr-solrj-4.0.0.jar;"
            + root + "trunk/apache-http/4.1.3/httpclient-4.1.3.jar;"
            + root + "trunk/apache-http/4.1.3/httpcore-4.1.4.jar;"
            + root + "trunk/apache-http/4.1.3/httpmime-4.1.3.jar;"
            + root + "trunk/out-default/production/SimagisLiveAccess;"
            + root + "trunk/apache-commons/lib/commons-dbutils-1.3.jar;"
            + root + "trunk/out-default/production/PlanePyramidSource3DHISTECH;"
            + root + "trunk/bin/Customer/cust-chmz/classes;"
            + root + "trunk/bin/plastics/classes;"
            + root + "trunk/out-default/production/RemotePlanePyramidImageIODICOM;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/commons-cli-1.2.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-audit-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-base64-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-core-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-filecache-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-hp-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-image-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-imageio-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-imageio-rle-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-iod-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-net-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-soundex-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-tool-dcm2dcm-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-tool-dcm2jpg-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-tool-dcm2txt-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-tool-dcm2xml-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-tool-dcmdir-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-tool-dcmecho-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-tool-dcmgpwl-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-tool-dcmhpqr-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-tool-dcmmv-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-tool-dcmmwl-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-tool-dcmof-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-tool-dcmqr-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-tool-dcmrcv-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-tool-dcmsnd-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-tool-dcmups-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-tool-dcmwado-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-tool-fixjpegls-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-tool-jpg2dcm-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-tool-logger-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-tool-pdf2dcm-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-tool-rgb2ybr-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-tool-txt2dcmsr-2.0.26.jar;"
            + root + "trunk/DICOM/jar/dcm4che-2.0.26/lib/dcm4che-tool-xml2dcm-2.0.26.jar;"
            + root + "trunk/out-default/production/RemotePlanePyramidImageIO;";
        String[] cmd = {
            root + "jre/bin/java", "-ea", "-esa", "-server", "-Xms128m", "-Xmx740m",
            "-Ds7.library.path=bin/lib",
            "-Djava.library.path=bin/lib;OpenSlide/openslide-win32",
            "-Dnet.algart.arrays.maxMappedMemory=2g",
            "-Ds7.lookAndFeel=System",
            "-classpath", classPath,
            "siams.Application", "--conf=bin/default.cfg"
        };
        ProcessBuilder processBuilder = new ProcessBuilder(cmd);
        processBuilder.directory(new File(root + "trunk"));
        processBuilder.redirectOutput(ProcessBuilder.Redirect.INHERIT);
        processBuilder.redirectError(ProcessBuilder.Redirect.INHERIT);
        final Process process = processBuilder.start();
        process.waitFor();
    }
}
